### ISSUE TITLE
Learn.co looks for test completion, but no tests are provided

### ISSUE THREAD

**Issue by psan2** [learn-co-curriculum/js-rails-as-api-using-fast-json-api#3]
May be interpreting this incorrectly, but Learn.co asks for completion of "Run local tests", but the learn command is unable to locate a spec folder for test specs.

**Comment by maxwellbenton** [comment]
Hi @psan2,

Thanks for catching this and providing feedback! You are correct - Learn was misinterpreting this code-along due to the `test` folder being present. The folder has been removed from this lesson and the solution, so this code-along should no longer behave like a lab in Learn.co

Thank you for contributing to a Learn.co lesson!
